name: CI for local {{ actionName }}
on:
  push:
    branches-ignore:
      - main

jobs:
  run-tests:
    if: github.repository == '{{githubOwner}}/{{githubRepository}}'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .github/actions/{{ actionName }}
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: install dependencies
        run: npm ci

      - name: run tests
        run: npm run test
