name: Grading workflow
on:
  push:
    paths:
      - ".github/workflows/stale-*.yml"
  workflow_dispatch:

jobs:
  grade-learner:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Grade {{ labName }} activity
        id: events
        uses: ./.github/actions/yaml-parser-action
        with:
          github-token: {% raw %}${{secrets.GITHUB_TOKEN}}{% endraw %}
          files: "stale-weekly.yml"
      - name: Grading results
        uses: githubtraining/looking-glass-action@{{ lookingGlassVersion }}
        with:
          github-token: {% raw %}${{secrets.GITHUB_TOKEN}}{% endraw %}
          feedback: {% raw %}${{ steps.events.outputs.reports }}{% endraw %}
  troubleshoot-activity:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: troubleshooting steps
        run: echo "To get started, change the on field in stale-weekly.yml."
