name: Grading workflow
on:
  push:
    paths:
      - ".github/workflows/stale-*.yml"
  workflow_dispatch:

jobs:
  grade-learner:
    if: github.event_name == 'push' # Apply additional filters as needed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Grade {{ title }} activity
        id: events
        uses: ./.github/actions/{{actionName}}
        with:
          github-token: {% raw %}${{secrets.GITHUB_TOKEN}}{% endraw %}

      - name: Grading results
        uses: githubtraining/looking-glass-action@{{ lookingGlassVersion }}
        with:
          github-token: {% raw %}${{secrets.GITHUB_TOKEN}}{% endraw %}
          feedback: {% raw %}${{ steps.events.outputs.reports }}{% endraw %}
  troubleshoot-activity:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: troubleshooting steps
        run: echo "" #Help the user to troubleshoot the activity
